baseURL = "https://www.serpentos.com/"
languageCode = "en-us"
title = "Serpent OS"
theme = "fresh"
copyright = "Copyright &copy; 2020 Serpent OS Developers<br />"

[params]
herotitle = "Under Heavy Development"
herolink = "https://github.com/serpent-linux/"
herolinktext = "Check our GitHub"
contact = "Send me a message and I will get back as soon as possible."

[permalinks]
    blog = "/blog/:year/:month/:day/:title/"

[menu]
    [[menu.nav]]
        name    = "about"
        pre = "<i class='fas fa-home'></i>"
        url     = "about"
        weight  = -1
    [[menu.nav]]
        name    = "blog"
        pre = "<i class='fas fa-list'></i>"
        url     = "blog"
        weight  = -2

    [[menu.social]]
        name = "rss"
        url = "/blog/index.xml"
        pre = "<i class='fas fa-rss'></i>"
        weight = -1

    [[menu.social]]
        name = "irc"
        url = "irc://chat.freenode.net/#serpentOS"
        pre = "<i class='fas fa-hashtag'></i>"
        weight = -2

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        disable = true
    [privacy.instagram]
        disable = true
    [privacy.twitter]
        disable = false
        enableDNT = false
        simple = false
    [privacy.vimeo]
        disable = true
    [privacy.youtube]
        privacyenhanced = true
